name: Trigger Repo B Tests

on:
  push:
    branches:
      - master

jobs:
  trigger-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in Repo B
        uses: peter-evans/repository-dispatch@v3
        #cypress-io/github-action@v6
        with:
          token: ${{ secrets.REPO_B_PATs }}
          repository: ElJentle/Pet_Cypress_Project
          event-type: run-tests 